#ifndef COMMON_CARAMELOS_H
#define COMMON_CARAMELOS_H
typedef enum {
	HUECO=-1,
	RED_BUTTON=0, 
	BLUE_BUTTON, //1
	GREEN_BUTTON, //2
	PURPLE_BUTTON, //3
	YELLOW_BUTTON,//4
	RED_HORBAR,  //5
	BLUE_HORBAR,  //6
	GREEN_HORBAR,//7
	PURPLE_HORBAR, //8
	YELLOW_HORBAR, //9
	RED_VERBAR, //10
	BLUE_VERBAR, //11
	GREEN_VERBAR, //12
	PURPLE_VERBAR, //13
	YELLOW_VERBAR, //14
	STAR, //15
	RELLENAR //16
} Caramelos;

#endif
