#ifndef __COMMON_CARAMELOS_MOVIMIENTOS_H__
#define __COMMON_CARAMELOS_MOVIMIENTOS_H__

typedef enum {
	CARAMELO_MOV_ARRIBA=1,
	CARAMELO_MOV_DERECHA, //2
	CARAMELO_MOV_ABAJO, //3
	CARAMELO_MOV_IZQ, //4
	CARAMELO_MOV_LIMBO, //5
	CARAMELO_MOV_NEW //6
} CaramelosMovimientos;



#endif
