#ifndef __COMMON_CARAMELOS_MOVIMIENTOS_H__
#define __COMMON_CARAMELOS_MOVIMIENTOS_H__

typedef enum {
	CARAMELO_MOV_ARRIBA=1,
	CARAMELO_MOV_DERECHA,
	CARAMELO_MOV_ABAJO,
	CARAMELO_MOV_IZQ,
	CARAMELO_MOV_LIMBO,
	CARAMELO_MOV_NEW
} CaramelosMovimientos;



#endif
